# Generated by Django 5.0 on 2024-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('items', models.TextField()),
                ('lat_long', models.CharField(max_length=100)),
                ('full_details', models.TextField()),
            ],
        ),
    ]
